### ISSUE TITLE
undefined reference to `CheckTransaction(CTransaction const&, CValidationState&, uint256, bool, int, bool)'

### ISSUE THREAD

**Issue by notatestuser** [zcoinofficial/zcoin#192]
Unable to compile on Ubuntu 16.04. Any ideas?
```
make[3]: Leaving directory '/root/code/zcoin/src/secp256k1'
  CXXLD    zcoind
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `ReadKeyValue(CWallet*, CDataStream&, CDataStream&, CWalletScanState&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
/root/code/zcoin/src/wallet/walletdb.cpp:446: undefined reference to `CheckTransaction(CTransaction const&, CValidationState&, uint256, bool, int, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [zcoind] Error 1
Makefile:3243: recipe for target 'zcoind' failed
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
make[2]: Leaving directory '/root/code/zcoin/src'
Makefile:7611: recipe for target 'install-recursive' failed
make[1]: Leaving directory '/root/code/zcoin/src'
Makefile:688: recipe for target 'install-recursive' failed
```

**Comment by typoworx-de** [comment]
I ran into the same problem. Seems to be an generic issue for all wallets basing on bitcoin source which has to do with openssl compatibility.
https://github.com/vergecurrency/VERGE/issues/48

**Comment by riordant** [comment]
Hi, it seems this was the fix https://github.com/bitcoin/bitcoin/commit/4ec3561eb3473638230ef780b41343bc6284b460
which has now been integrated. Can you try compiling with the latest client?

**Comment by devwarrior777** [comment]
Hi, I have sanity checked that the `scriptnum10` code is indeed in the latest client. I have just built it three times with `master` at version 0.13.5.8 with no issues (on an ubuntu 16-04 VM)

May we close this issue?

**Comment by devwarrior777** [comment]
I have checked the integration exists in `master` and builds on Ubuntu 16-04.

May we close this please?

**Comment by notatestuser** [comment]
Sure, thanks
