### ISSUE TITLE
compilation fails with Db 6.2

### ISSUE THREAD

**Issue by rbiegel** [zcoinofficial/zcoin#33]
```
db.cpp: In member function ‘void CDBEnv::EnvShutdown()’:
db.cpp:40:16: error: call of overloaded ‘DbEnv(int)’ is ambiguous
         DbEnv(0).remove(path.string().c_str(), 0);
                ^
In file included from db.h:14:0,
                 from db.cpp:6:
/usr/include/db6.2/db_cxx.h:916:2: note: candidate: DbEnv::DbEnv(const DbEnv&)
  DbEnv(const DbEnv &);
  ^
In file included from db.h:14:0,
                 from db.cpp:6:
/usr/include/db6.2/db_cxx.h:518:2: note: candidate: DbEnv::DbEnv(DB_ENV*)
  DbEnv(DB_ENV *dbenv);
  ^
/usr/include/db6.2/db_cxx.h:516:2: note: candidate: DbEnv::DbEnv(u_int32_t)
  DbEnv(u_int32_t flags);
  ^
```
Fix from bitcoin: https://github.com/bitcoin/bitcoin/pull/8626/commits/323a5fe06af43d3922a435e696d6c52acc6fade1

**Comment by nopslide** [comment]
we tried with 4.8

**Comment by barrystyle** [comment]
works fine with 5.3

**Comment by aizensou** [comment]
Berkeley DB 6.2 isn't supported.
