### ISSUE TITLE
Compile on Alpine 3.8 fails - Backtrace not available - includes fix

### ISSUE THREAD

**Issue by jTd7bPLFb** [zcoinofficial/zcoin#923]
<h2>When compiling on Alpine 3.8, there is no backtrace and compilation fails for the tor part. </h2>

Error:
<pre>
tor/src/lib/libtor-err.a(backtrace.o): In function `crash_handler':
/compile/ZCOIN/src/tor/src/lib/err/backtrace.c:190: undefined reference to `backtrace'
</pre>

<h2>Here is a small patch to fix this. </h2>

<pre>
# diff src/tor/src/lib/err/backtrace.c.ori src/tor/src/lib/err/backtrace.c 

diff src/tor/src/lib/err/backtrace.c.ori src/tor/src/lib/err/ba
cktrace.c 
--- src/tor/src/lib/err/backtrace.c.ori
+++ src/tor/src/lib/err/backtrace.c
@@ -60,7 +60,7 @@
 #if defined(HAVE_EXECINFO_H) && defined(HAVE_BACKTRACE) && \
   defined(HAVE_BACKTRACE_SYMBOLS_FD) && defined(HAVE_SIGACTION) && \
   defined(HAVE_PTHREAD_H)
-#define USE_BACKTRACE
+#define NO_USE_BACKTRACE // Workaround for Alpine - no backtrace
 #endif
 
 #if !defined(USE_BACKTRACE)
 ' > patch03.diff
patch -p1 src/tor/src/lib/err/backtrace.c < patch03.diff
</pre>

**Comment by a-bezrukov** [comment]
We cannot apply this patch as Alpine Linux is not in the list of supported OSes. As lack of backtrace in Alpine Linux is a  [known issue](https://gitlab.alpinelinux.org/alpine/aports/-/issues/5079) and it doesn't seem to have an easy solution, please run confugure --enable-crash-hooks
